ovst-run-net-test works for netpipe and iperf

diff --git a/bin/ovst-setup-network b/bin/ovst-setup-network
--- a/bin/ovst-setup-network
+++ b/bin/ovst-setup-network
@@ -73,3 +73,8 @@ elif [ ${network_type} == "ovs" ]; then
   ovs-vsctl add-port ${ovs_bridge} ${network_device}
   ifconfig ${network_device} 0.0.0.0 up
 fi
+else
+  echo "error: ${network_type} unknown network type"
+  echo $usage
+  exit 1
+fi
diff --git a/bin/ovst-start-guest b/bin/ovst-start-guest
--- a/bin/ovst-start-guest
+++ b/bin/ovst-start-guest
@@ -2,6 +2,12 @@
 
 usage="usage: $0 bridge|ovs <base_image> <guest_name> [virt_system (default KVM - only virt system supported so far)]"
 
+user=`whoami`
+if [ $user != "root" ]; then
+  echo 'must be root'
+  exit 1
+fi
+
 if [ -z $3 ]; then
   echo $usage
   exit 1
@@ -30,7 +36,7 @@ elif [ ${network_type} == "ovs" ]; then
   DOWN_SCRIPT='/usr/local/etc/ovs-ifdown'
 
 else
-  echo 'error: ${network_type} unknown network type'
+  echo "error: ${network_type} unknown network type"
   echo $usage
   exit 1
 fi
